import * as Plot from "@observablehq/plot";

import { parse } from "csv-parse/browser/esm/sync";
import { identity, keys } from "lodash-es";
import "./style.css";

// load data
async function initPlot() {
  const dataFileRequest = await fetch("/tradeGraphsStats_gravity.csv");

  if (dataFileRequest.ok) {
    const tradeGraphStatsCSV = await dataFileRequest.text();

    const tradeGraphStats = parse<Record<string, number>>(tradeGraphStatsCSV, {
      columns: true,
      cast: true,
    });
    const height = 300;
    const colors: Record<string, string> = {
      generated: "#73D24B",
      "reported network": "#0049af",
      "generated by aggregation": "#7bdf51",
      "good as reported": "#BECFE7",
      "generated by gravity": "#9df876",
      "generated by year ratios": "#d2f7c2",
      "unsuccessful generation": "#d8d8d8",
      "resulting network": "#73D24B",
    };
    const colorScale = Plot.scale({
      color: {
        range: keys(colors).map((c) => colors[c]),
        domain: keys(colors),
      },
    });

    const densityData = tradeGraphStats.flatMap((data) => [
      {
        year: new Date(data.year + ""),
        density: data.generatedNetworkDensity,
        symbol: "resulting network",
      },
      {
        year: new Date(data.year + ""),
        density: data.reportedNetworkDensity,
        symbol: "reported network",
      },
    ]);

    const densityDomain = ["resulting network", "reported network"];
    const densityPlot = Plot.plot({
      height,
      color: {
        legend: true,
        range: densityDomain.map((d) => colorScale.apply(d)),
        domain: densityDomain,
      },
      y: { grid: true, label: "Trade network density" },
      marks: [
        Plot.ruleY([0]),
        Plot.lineY(densityData, {
          x: "year",
          y: "density",
          stroke: "symbol",
        }),
      ],
    });

    const densityDiv = document.querySelector("#density-plot");
    if (densityDiv) densityDiv.append(densityPlot);

    const valueShareData = tradeGraphStats.flatMap((data) => {
      const totalTreatedValue =
        data.generated_by_aggregation_value +
        data.generated_by_gravity_value +
        data.generated_by_years_ratio_value;
      const totalFailedValue = data.failed_value;
      const totalNeededTreatment = totalFailedValue + totalTreatedValue;
      return [
        {
          year: new Date(data.year + ""),
          valueShare: data.generated_by_aggregation_value / totalTreatedValue,
          valueShareSymbol: "generated by aggregation",
        },
        {
          year: new Date(data.year + ""),
          valueShare: data.generated_by_gravity_value / totalTreatedValue,
          valueShareSymbol: "generated by gravity",
        },
        {
          year: new Date(data.year + ""),
          valueShare: data.generated_by_years_ratio_value / totalTreatedValue,
          valueShareSymbol: "generated by year ratios",
        },

        {
          year: new Date(data.year + ""),
          totalValueShare:
            data.good_as_reported_value /
            (totalNeededTreatment + data.good_as_reported_value),
          symbol: "good as reported",
        },
        {
          year: new Date(data.year + ""),
          totalValueShare:
            totalTreatedValue /
            (totalNeededTreatment + data.good_as_reported_value),
          symbol: "generated",
        },
        {
          year: new Date(data.year + ""),
          totalValueShare:
            totalFailedValue /
            (totalNeededTreatment + data.good_as_reported_value),
          symbol: "unsuccessful generation",
        },
      ];
    });
    const valueShareDomain = [
      "generated by year ratios",
      "generated by gravity",
      "generated by aggregation",
    ];
    const valueSharePlot = Plot.plot({
      height,
      y: {
        grid: true,
        label: "Share of generated trade flow value",
      },
      color: {
        legend: true,
        range: valueShareDomain.map((d) => colorScale.apply(d)),
        domain: valueShareDomain,
      },
      marks: [
        Plot.areaY(
          valueShareData.filter((d) => identity(d.valueShare)),
          Plot.stackY({ x: "year", y: "valueShare", fill: "valueShareSymbol" }),
        ),

        Plot.ruleY([0, 1]),
      ],
    });
    const valueShareDiv = document.querySelector(
      "#transformations-value-share-plot",
    );
    if (valueShareDiv) valueShareDiv.append(valueSharePlot);
    const totalValueShareDomain = [
      "unsuccessful generation",
      "generated",
      "good as reported",
    ];
    const totalValueSharePlot = Plot.plot({
      height,
      y: { grid: true, label: "Share of total reported trade flow value" },

      color: {
        legend: true,
        range: totalValueShareDomain.map((d) => colorScale.apply(d)),
        domain: totalValueShareDomain,
      },
      marks: [
        Plot.areaY(
          valueShareData.filter((d) => identity(d.totalValueShare)),
          Plot.stackY({ x: "year", y: "totalValueShare", fill: "symbol" }),
        ),
        Plot.ruleY([0, 1]),
      ],
    });

    const totalValueShareDiv = document.querySelector("#value-share-plot");
    if (totalValueShareDiv) totalValueShareDiv.append(totalValueSharePlot);
  }
}

initPlot().then(() => console.log("done"));
