import { MultiDirectedGraph } from "graphology";

import { GPHStatusType } from "./GPH";

export type RICType = "GPH_entity" | "group" | "locality" | "geographical_area" | "colonial_area";

export interface RICentity {
  RICname: string;
  type: RICType;
  parent_entity?: string;
  GPH_code?: string;
}

export type EntityType = "RIC" | "GPH" | "GPH-AUTONOMOUS" | "GPH-AUTONOMOUS-CITED" | "ROTW";

export interface EntityNodeAttributes {
  label: string;
  reporting: boolean;
  reportingByAggregateInto?: boolean;
  reportingBySplit?: boolean;
  ricType: RICType;
  entityType: EntityType;
  cited?: boolean;
  gphStatus?: GPHStatusType;
  ricParent?: string;
  totalBilateralTrade?: number;
  type: "entity";
  lat?: number;
  lng?: number;
}
export interface ResolutionNodeAttributes {
  label: string;
  type: "resolution";
}

export type EntityResolutionLabelType = "AGGREGATE_INTO" | "SPLIT" | "SPLIT_OTHER";
export type TradeLabelType = "REPORTED_TRADE" | "GENERATED_TRADE" | "TRADE_FROM_TO_AGGREGATE_REPORTER";

export type EdgeLabelType = TradeLabelType | EntityResolutionLabelType;

export type FlowValueImputationMethod =
  | "aggregation"
  | "split_to_one"
  | "split_by_years_ratio"
  | "split_by_mirror_ratio"
  | "split_by_gravity";

export type TradeEdgeStatus =
  | "toTreat" // trade flows which includes one trading partner to aggregate/split
  | "ok" // trade flows which are good to include in calculations
  | "ignore_internal" // flows to ignore as they describe internal trade
  | "ignore_resolved" // flows successfully transformed and thus should be ignored
  | "ignore_duplicate" // flows to ignore as their transformation leads to a duplicated trade flow
  | "split_failed_no_ratio" // flows we couldn't split by the ratio method
  | "split_failed_error" // an error occurred in the ratio method attempt (splitting reporter, no more partners after areas dis-ambiguisation)
  | "split_only_partial"; // flows we could only split partially by the ratio method

export interface TradeEdgeAttributes {
  labels: Set<EdgeLabelType>;
  label?: string;
  // value can be undefinde for to impute trade flows
  value?: number;
  // indicate that the value has been generated by aggregated only a partial set of entities
  partial?: string;
  // name of reporter used for to generate this trade flow
  generatedFrom?: string;
  // method used to generate trade value
  valueGeneratedBy?: FlowValueImputationMethod[];

  reportedBy: string;
  originalReporters?: Set<string>;

  status?: TradeEdgeStatus;
  notes?: string;
  mergedIn?: string[];
  valueToSplit?: number;
  newReporter?: string;
  newPartners?: string;
  originalReportedTradeFlowId?: string;
  type: "trade";
}
export type GraphAttributes = { year: number };
export type GraphType = MultiDirectedGraph<
  EntityNodeAttributes,
  TradeEdgeAttributes | ResolutionEdgeAttributes,
  GraphAttributes
>;
export type GraphEntityPartiteType = MultiDirectedGraph<EntityNodeAttributes, TradeEdgeAttributes, GraphAttributes>;

export interface ResolutionEdgeAttributes {
  labels: Set<EntityResolutionLabelType>;
  type: "resolution";
}
export type GraphResolutionPartiteType = MultiDirectedGraph<
  EntityNodeAttributes,
  ResolutionEdgeAttributes,
  GraphAttributes
>;

export type TradeVizEdgeAttribute =
  | {
      labels: Set<EdgeLabelType | EntityResolutionLabelType>;
      status: Set<TradeEdgeStatus>;

      maxExpImp?: number;
      //TODO: add a combiend status ?

      importerValue?: number;
      importerPartial?: string;
      importerGeneratedFrom?: string;
      importerValueGeneratedBy?: FlowValueImputationMethod[];
      importerReportedBy: string;
      importerOriginalReporters?: Set<string>;

      importerStatus?: TradeEdgeStatus;
      importerNotes?: string;
      importerMergedIn?: string[];
      importerValueToSplit?: number;
      //importerOriginalReportedTradeFlowId?: string;
      exporterValue?: number;
      exporterPartial?: string;
      exporterGeneratedFrom?: string;
      exporterValueGeneratedBy?: FlowValueImputationMethod[];
      exporterReportedBy: string;
      exporterOriginalReporters?: Set<string>;

      exporterStatus?: TradeEdgeStatus;
      exporterNotes?: string;
      exporterMergedIn?: string[];
      exporterValueToSplit?: number;
      //exporterOriginalReportedTradeFlowId?: string;
      type: "trade" | "trade&resolution";
    }
  | {
      labels: Set<EdgeLabelType | EntityResolutionLabelType>;
      type: "resolution" | "trade&resolution";
    };
